### ISSUE TITLE
Marketing Strategy

### ISSUE THREAD

**Issue by ChetanRajput** [ChetanRajput/Marketing-Strategy#1]
**INTRODUCTION**

We have researched the **Marketing Strategy** based on the trends in the mobile phone marketing and developed the idea to make a software that will help the smartphone manufacturers to build a phone mostly based on the customer demand. 

Basically an authenticated account will require to access the software which will be provided at the time of software purchase. Software will ask for the information like the smartphone brand name , price range and many parameters like that. Based on the information provided by the user the software will analyse the context by comparing it.

**ADVANTAGES**

On the basis of analysis done by software and feedback given by the customer the **Research and Development** team can build an hardware which will be more useful for users and will be technically powerful which will  ultimately increase the sell in market.

**Comment by KetanArwat** [comment]
Ass

**Comment by KetanArwat** [comment]
This system will help smart-phone companies provide features the customers actually want. Good Job :+1:

**Comment by mamtapanda26** [comment]
Good work....

**Comment by SharIsh30** [comment]
Nice work... Keep it up!!

**Comment by truptisuryavanshi** [comment]
Nice Research Chetan.....Good Job...

**Comment by anita1620** [comment]
good job guys...

**Comment by blizz23** [comment]
Nice concept..the customers can now get the features they want.

**Comment by shub55555** [comment]
goin' gud bro.. All the bst...!!!

**Comment by vedhaspathak** [comment]
Nice concept this will realy help manufacturers to create a phone as per consumer's requirements and not according to CEO's point if view.

**Comment by DSnehal28** [comment]
Nice Concept..Gonna be very Helpful..!!!!

**Comment by PDDhongade9** [comment]
very informative and innovative idea!!!!!

**Comment by shreya-snehal-vaishnavi** [comment]
Good idea..nice concept

**Comment by vivek-omkar-amey** [comment]
Goood job keep it up!!
